/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zaqqaz130;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author zaqqaz130
 */
public class CardMaker extends javax.swing.JFrame {

    /**
     * Creates new form CardMaker
     */
    public CardMaker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEnterDetails = new javax.swing.JPanel();
        lblEnterName = new javax.swing.JLabel();
        txtEnterName = new javax.swing.JTextField();
        lblEnterTitle = new javax.swing.JLabel();
        txtEnterTitle = new javax.swing.JTextField();
        lblEnterPhone = new javax.swing.JLabel();
        txtEnterPhone = new javax.swing.JTextField();
        lblEnterEmail = new javax.swing.JLabel();
        txtEnterEmail = new javax.swing.JTextField();
        pnlChangeColourName = new javax.swing.JPanel();
        pnlChangeColourTitle = new javax.swing.JPanel();
        pnlChangeColourPhone = new javax.swing.JPanel();
        pnlChangeColourEmail = new javax.swing.JPanel();
        pnlPreview = new javax.swing.JPanel();
        tabPanePreviews = new javax.swing.JTabbedPane();
        pnlTabCardPreviewContainer = new javax.swing.JPanel();
        pnlCardPreview = new javax.swing.JPanel();
        lblCardPreviewName = new javax.swing.JLabel();
        lblCardPreviewTitle = new javax.swing.JLabel();
        lblCardPreviewPhone = new javax.swing.JLabel();
        lblCardPreviewEmail = new javax.swing.JLabel();
        menuMain = new javax.swing.JMenuBar();
        menuMainFile = new javax.swing.JMenu();
        menuMainFileExit = new javax.swing.JMenuItem();
        menuMainEdit = new javax.swing.JMenu();
        menuMainView = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Business Card Maker");

        pnlEnterDetails.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Your Details:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.black));

        lblEnterName.setText("Enter your Name:");

        txtEnterName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEnterName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UpdateName(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UpdateName(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UpdateName(evt);
            }
        });

        lblEnterTitle.setText("Enter your Title:");

        txtEnterTitle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEnterTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UpdateTitle(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UpdateTitle(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UpdateTitle(evt);
            }
        });

        lblEnterPhone.setText("Enter your Phone Number:");

        txtEnterPhone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEnterPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UpdatePhone(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UpdatePhone(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UpdatePhone(evt);
            }
        });

        lblEnterEmail.setText("Enter your Email:");

        txtEnterEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEnterEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UpdateEmail(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UpdateEmail(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UpdateEmail(evt);
            }
        });

        pnlChangeColourName.setBackground(java.awt.Color.black);
        pnlChangeColourName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlChangeColourName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeColourName(evt);
            }
        });

        javax.swing.GroupLayout pnlChangeColourNameLayout = new javax.swing.GroupLayout(pnlChangeColourName);
        pnlChangeColourName.setLayout(pnlChangeColourNameLayout);
        pnlChangeColourNameLayout.setHorizontalGroup(
            pnlChangeColourNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        pnlChangeColourNameLayout.setVerticalGroup(
            pnlChangeColourNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        pnlChangeColourTitle.setBackground(java.awt.Color.black);
        pnlChangeColourTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlChangeColourTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeColourTitle(evt);
            }
        });

        javax.swing.GroupLayout pnlChangeColourTitleLayout = new javax.swing.GroupLayout(pnlChangeColourTitle);
        pnlChangeColourTitle.setLayout(pnlChangeColourTitleLayout);
        pnlChangeColourTitleLayout.setHorizontalGroup(
            pnlChangeColourTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        pnlChangeColourTitleLayout.setVerticalGroup(
            pnlChangeColourTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        pnlChangeColourPhone.setBackground(java.awt.Color.black);
        pnlChangeColourPhone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlChangeColourPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeColourPhone(evt);
            }
        });

        javax.swing.GroupLayout pnlChangeColourPhoneLayout = new javax.swing.GroupLayout(pnlChangeColourPhone);
        pnlChangeColourPhone.setLayout(pnlChangeColourPhoneLayout);
        pnlChangeColourPhoneLayout.setHorizontalGroup(
            pnlChangeColourPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        pnlChangeColourPhoneLayout.setVerticalGroup(
            pnlChangeColourPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        pnlChangeColourEmail.setBackground(java.awt.Color.black);
        pnlChangeColourEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlChangeColourEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangeColourEmail(evt);
            }
        });

        javax.swing.GroupLayout pnlChangeColourEmailLayout = new javax.swing.GroupLayout(pnlChangeColourEmail);
        pnlChangeColourEmail.setLayout(pnlChangeColourEmailLayout);
        pnlChangeColourEmailLayout.setHorizontalGroup(
            pnlChangeColourEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        pnlChangeColourEmailLayout.setVerticalGroup(
            pnlChangeColourEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlEnterDetailsLayout = new javax.swing.GroupLayout(pnlEnterDetails);
        pnlEnterDetails.setLayout(pnlEnterDetailsLayout);
        pnlEnterDetailsLayout.setHorizontalGroup(
            pnlEnterDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnterDetailsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnterDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnterDetailsLayout.createSequentialGroup()
                        .addGroup(pnlEnterDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEnterPhone)
                            .addComponent(lblEnterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(pnlEnterDetailsLayout.createSequentialGroup()
                        .addGroup(pnlEnterDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEnterTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEnterName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlEnterDetailsLayout.createSequentialGroup()
                                .addGroup(pnlEnterDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtEnterEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                    .addComponent(txtEnterPhone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEnterTitle, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEnterName, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlEnterDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnlChangeColourName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlChangeColourTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlChangeColourPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pnlChangeColourEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(33, Short.MAX_VALUE))))
        );
        pnlEnterDetailsLayout.setVerticalGroup(
            pnlEnterDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnterDetailsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEnterName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnterDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEnterName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlChangeColourName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnterTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnterDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEnterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlChangeColourTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnterPhone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnterDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEnterPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEnterDetailsLayout.createSequentialGroup()
                        .addComponent(pnlChangeColourPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnterDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlEnterDetailsLayout.createSequentialGroup()
                        .addComponent(lblEnterEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEnterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlChangeColourEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        pnlPreview.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preview:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        pnlCardPreview.setBackground(java.awt.Color.white);
        pnlCardPreview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblCardPreviewName.setText("Your Name");

        lblCardPreviewTitle.setText("Your Title");

        lblCardPreviewPhone.setText("Your Phone Number");

        lblCardPreviewEmail.setText("Your Email");

        javax.swing.GroupLayout pnlCardPreviewLayout = new javax.swing.GroupLayout(pnlCardPreview);
        pnlCardPreview.setLayout(pnlCardPreviewLayout);
        pnlCardPreviewLayout.setHorizontalGroup(
            pnlCardPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardPreviewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCardPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCardPreviewName)
                    .addComponent(lblCardPreviewTitle)
                    .addComponent(lblCardPreviewPhone)
                    .addComponent(lblCardPreviewEmail))
                .addContainerGap(283, Short.MAX_VALUE))
        );
        pnlCardPreviewLayout.setVerticalGroup(
            pnlCardPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardPreviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCardPreviewName)
                .addGap(18, 18, 18)
                .addComponent(lblCardPreviewTitle)
                .addGap(18, 18, 18)
                .addComponent(lblCardPreviewPhone)
                .addGap(18, 18, 18)
                .addComponent(lblCardPreviewEmail)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlTabCardPreviewContainerLayout = new javax.swing.GroupLayout(pnlTabCardPreviewContainer);
        pnlTabCardPreviewContainer.setLayout(pnlTabCardPreviewContainerLayout);
        pnlTabCardPreviewContainerLayout.setHorizontalGroup(
            pnlTabCardPreviewContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabCardPreviewContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCardPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTabCardPreviewContainerLayout.setVerticalGroup(
            pnlTabCardPreviewContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabCardPreviewContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCardPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPanePreviews.addTab("Card Preview", pnlTabCardPreviewContainer);

        javax.swing.GroupLayout pnlPreviewLayout = new javax.swing.GroupLayout(pnlPreview);
        pnlPreview.setLayout(pnlPreviewLayout);
        pnlPreviewLayout.setHorizontalGroup(
            pnlPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanePreviews)
                .addContainerGap())
        );
        pnlPreviewLayout.setVerticalGroup(
            pnlPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPreviewLayout.createSequentialGroup()
                .addComponent(tabPanePreviews)
                .addContainerGap())
        );

        menuMainFile.setText("File");

        menuMainFileExit.setText("Exit");
        menuMainFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMainFileExitActionPerformed(evt);
            }
        });
        menuMainFile.add(menuMainFileExit);

        menuMain.add(menuMainFile);

        menuMainEdit.setText("Edit");
        menuMain.add(menuMainEdit);

        menuMainView.setText("View");
        menuMain.add(menuMainView);

        setJMenuBar(menuMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlEnterDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(pnlPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPreview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlEnterDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMainFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMainFileExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuMainFileExitActionPerformed

    private void UpdateName(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpdateName
        lblCardPreviewName.setText(txtEnterName.getText());
    }//GEN-LAST:event_UpdateName

    private void UpdateTitle(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpdateTitle
        lblCardPreviewTitle.setText(txtEnterTitle.getText());
    }//GEN-LAST:event_UpdateTitle

    private void UpdatePhone(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpdatePhone
        lblCardPreviewPhone.setText(txtEnterPhone.getText());
    }//GEN-LAST:event_UpdatePhone

    private void UpdateEmail(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UpdateEmail
        lblCardPreviewEmail.setText(txtEnterEmail.getText());
    }//GEN-LAST:event_UpdateEmail

    private void ChangeColourName(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeColourName
        Color userColour = JColorChooser.showDialog(null, "Hi", Color.yellow);
        lblCardPreviewName.setForeground(userColour);
        pnlChangeColourName.setBackground(userColour);
    }//GEN-LAST:event_ChangeColourName

    private void ChangeColourTitle(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeColourTitle
        Color userColour = JColorChooser.showDialog(null, "Hi", Color.yellow);
        lblCardPreviewTitle.setForeground(userColour);
        pnlChangeColourTitle.setBackground(userColour);
    }//GEN-LAST:event_ChangeColourTitle

    private void ChangeColourPhone(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeColourPhone
        Color userColour = JColorChooser.showDialog(null, "Hi", Color.yellow);
        lblCardPreviewPhone.setForeground(userColour);
        pnlChangeColourPhone.setBackground(userColour);
    }//GEN-LAST:event_ChangeColourPhone

    private void ChangeColourEmail(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangeColourEmail
        Color userColour = JColorChooser.showDialog(null, "Hi", Color.yellow);
        lblCardPreviewEmail.setForeground(userColour);
        pnlChangeColourEmail.setBackground(userColour);
    }//GEN-LAST:event_ChangeColourEmail

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CardMaker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCardPreviewEmail;
    private javax.swing.JLabel lblCardPreviewName;
    private javax.swing.JLabel lblCardPreviewPhone;
    private javax.swing.JLabel lblCardPreviewTitle;
    private javax.swing.JLabel lblEnterEmail;
    private javax.swing.JLabel lblEnterName;
    private javax.swing.JLabel lblEnterPhone;
    private javax.swing.JLabel lblEnterTitle;
    private javax.swing.JMenuBar menuMain;
    private javax.swing.JMenu menuMainEdit;
    private javax.swing.JMenu menuMainFile;
    private javax.swing.JMenuItem menuMainFileExit;
    private javax.swing.JMenu menuMainView;
    private javax.swing.JPanel pnlCardPreview;
    private javax.swing.JPanel pnlChangeColourEmail;
    private javax.swing.JPanel pnlChangeColourName;
    private javax.swing.JPanel pnlChangeColourPhone;
    private javax.swing.JPanel pnlChangeColourTitle;
    private javax.swing.JPanel pnlColourName1;
    private javax.swing.JPanel pnlEnterDetails;
    private javax.swing.JPanel pnlPreview;
    private javax.swing.JPanel pnlTabCardPreviewContainer;
    private javax.swing.JTabbedPane tabPanePreviews;
    private javax.swing.JTextField txtEnterEmail;
    private javax.swing.JTextField txtEnterName;
    private javax.swing.JTextField txtEnterPhone;
    private javax.swing.JTextField txtEnterTitle;
    // End of variables declaration//GEN-END:variables
}
