/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.zaqqaz130;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.text.Highlighter;
//import sun.awt.X11.Screen;
import com.zaqqaz130.critter.*;
//import sun.misc.GC;
import java.*;
import java.awt.Image;
import java.awt.image.ImageProducer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author zaqqaz130
 */
public class Main extends JFrame {

    private int sumTotal, numOne, numTwo, answerCorrect, answerIncorrect,
            randOper;
    private final Random rand = new Random();
    private String guess, operChar;
    private StringBuffer passWord;
    // private boolean isCorrect;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAnswer = new javax.swing.JButton();
        lblNumOne = new javax.swing.JLabel();
        lblOperator = new javax.swing.JLabel();
        lblNumTwo = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        lblOutput = new javax.swing.JLabel();
        txtGuess = new javax.swing.JTextField();
        lblCorrect = new javax.swing.JLabel();
        lblIncorrect = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        btnShowAnswer = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblEnterPassword = new javax.swing.JLabel();
        lblEncryptedPassword = new javax.swing.JLabel();
        btnEncrypt = new javax.swing.JButton();
        txtEnterPassword = new javax.swing.JPasswordField();
        btnDecrypt = new javax.swing.JButton();
        lblDecryptedPassword = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtColours = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        textArea1 = new java.awt.TextArea();
        button1 = new java.awt.Button();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        pnlColor = new javax.swing.JPanel();
        btnColorz = new javax.swing.JButton();
        txtSizeX = new javax.swing.JTextField();
        txtSizeY = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java thingy");

        jLabel1.setText("Type your answer here:");

        btnAnswer.setLabel("Answer");
        btnAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnswerActionPerformed(evt);
            }
        });

        lblNumOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumOne.setText("One");

        lblOperator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOperator.setText("+");

        lblNumTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumTwo.setText("Two");

        btnStart.setLabel("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        lblOutput.setText("Is your answer correct?");

        txtGuess.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                checkAnswer();
            }
        });

        lblCorrect.setText("Correct Answers:");

        lblIncorrect.setText("Incorrect Answers:");

        lblTime.setText("Time:");

        btnShowAnswer.setText("Show Answer");
        btnShowAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAnswerActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIncorrect)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblOutput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAnswer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumOne, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
                                    .addComponent(lblOperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNumTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(116, 116, 116))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCorrect)
                        .addGap(52, 52, 52)
                        .addComponent(btnShowAnswer)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTime)
                            .addComponent(jButton2))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(btnAnswer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStart)
                            .addComponent(txtGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNumOne)
                                .addGap(29, 29, 29))
                            .addComponent(lblOperator))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumTwo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblOutput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCorrect)
                    .addComponent(btnShowAnswer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIncorrect)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        lblNumOne.getAccessibleContext().setAccessibleName("lblOne");
        lblOperator.getAccessibleContext().setAccessibleName("lblOperator");
        lblNumTwo.getAccessibleContext().setAccessibleName("lblTwo");
        btnStart.getAccessibleContext().setAccessibleName("btnStart");

        jTabbedPane1.addTab("Hello", jPanel1);

        lblEnterPassword.setText("Enter a Password");

        lblEncryptedPassword.setText("Your Encrypted Password Will Appear Here");

        btnEncrypt.setText("Encrypt");
        btnEncrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncryptActionPerformed(evt);
            }
        });

        btnDecrypt.setText("Decrypt");
        btnDecrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecryptActionPerformed(evt);
            }
        });

        lblDecryptedPassword.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        lblDecryptedPassword.setText("Your Decrypted Password Will Appear Here");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEnterPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtEnterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEncrypt))
                    .addComponent(lblEncryptedPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDecrypt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDecryptedPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEnterPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEncrypt)
                    .addComponent(txtEnterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEncryptedPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDecrypt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDecryptedPassword)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Goodbye", jPanel2);

        jScrollPane1.setAutoscrolls(true);

        txtColours.setBackground(new java.awt.Color(32, 202, 209));
        jScrollPane1.setViewportView(txtColours);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jEditorPane1.setBackground(new java.awt.Color(231, 170, 54));
        jScrollPane2.setViewportView(jEditorPane1);

        button1.setLabel("button1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                woo(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hl(evt);
            }
        });
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                rects(evt);
            }
        });

        pnlColor.setBackground(new java.awt.Color(227, 139, 48));
        pnlColor.setForeground(new java.awt.Color(226, 21, 104));

        javax.swing.GroupLayout pnlColorLayout = new javax.swing.GroupLayout(pnlColor);
        pnlColor.setLayout(pnlColorLayout);
        pnlColorLayout.setHorizontalGroup(
            pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        pnlColorLayout.setVerticalGroup(
            pnlColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnColorz.setText("jButton2");
        btnColorz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorzActionPerformed(evt);
            }
        });

        txtSizeX.setText("15");

        txtSizeY.setText("25");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pnlColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 820, Short.MAX_VALUE)
                        .addComponent(btnColorz))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSizeX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSizeY, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnColorz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSizeX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSizeY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel4);

        jPanel6.setBackground(new java.awt.Color(231, 151, 13));
        jPanel6.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("b1.jpg"))); // NOI18N
        jPanel6.add(jLabel2);
        jLabel2.setBounds(30, 20, 190, 110);

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jButton4)
                .addContainerGap(699, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", jPanel5);

        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jMenuBar1.setBorderPainted(false);

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Colours");

        jMenuItem3.setText("Background");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        genMoreNums();
        //  lblTime.setText("Time: " + tmr.);
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnswerActionPerformed
        checkAnswer();
    }//GEN-LAST:event_btnAnswerActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Color userColour = JColorChooser.showDialog(null, "Hi", Color.yellow);
        // this.getContentPane().setBackground(userColour);
        jTabbedPane1.getSelectedComponent().setBackground(userColour);
        //  jTabbedPane1.add(txtEnterPassword.getText(), createRootPane().add(jPanel1));
        jTabbedPane1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        // jTabbedPane1.add(btnStart);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnShowAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAnswerActionPerformed
        btnShowAnswer.setText(String.valueOf(sumTotal));
    }//GEN-LAST:event_btnShowAnswerActionPerformed

    private void btnEncryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncryptActionPerformed
        passWord = new StringBuffer(txtEnterPassword.getText());
        int temp = 0;
        for (int i = 0; i < passWord.length(); i++) {
            temp = (int) passWord.charAt(i);
            temp = temp + 1;
            passWord.setCharAt(i, (char) temp);
        }
        lblEncryptedPassword.setText(String.valueOf(passWord));

    }//GEN-LAST:event_btnEncryptActionPerformed

    private void btnDecryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecryptActionPerformed
        int temp = 0;
        for (int i = 0; i < passWord.length(); i++) {
            temp = (int) passWord.charAt(i);
            temp = temp - 1;
            passWord.setCharAt(i, (char) temp);
        }
        lblDecryptedPassword.setText(String.valueOf(passWord));
    }//GEN-LAST:event_btnDecryptActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (int i = 0; i < 100; i++) {
            txtColours.setText(txtColours.getText() + "Hello\n");
            jEditorPane1.setText(txtColours.getText() + "Hello\n");
            int r, g, b;
            r = rand.nextInt(255) + 1;
            g = rand.nextInt(255) + 1;
            b = rand.nextInt(255) + 1;

            txtColours.setBackground(new Color(r, g, b).brighter());
            txtColours.setForeground(new Color(r, g, b));

            jEditorPane1.setBackground(new Color(r, g, b).brighter());
            jEditorPane1.setForeground(new Color(r, g, b));
            jEditorPane1.setSelectionStart(i);
            jEditorPane1.setSelectionEnd(i + 5);
            jEditorPane1.setSelectionColor(new Color(r, g, b));

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        for (int i = 0; i < 10; i++) {
            textArea1.setText(textArea1.getText() + "Hello\n");
            textArea1.setBackground(Color.red);

        }

    }//GEN-LAST:event_button1ActionPerformed

    private void btnColorzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorzActionPerformed
        Graphics G = null;
        for (int i = 0; i < 10; i++) {
            int r, g, b;
            r = rand.nextInt(255) + 1;
            g = rand.nextInt(255) + 1;
            b = rand.nextInt(255) + 1;

            int x, y;
            x = rand.nextInt(800);
            y = rand.nextInt(100) + 300;

            int xx, yy;
            xx = rand.nextInt(10);
            yy = rand.nextInt(10);

            // pnlColor.setBackground(new Color(r,g,b));
            G = this.getGraphics();
            G.setColor(new Color(r, g, b));
            G.fillRect(x, y, xx, yy);
            pnlColor.paint(G);
        }


    }//GEN-LAST:event_btnColorzActionPerformed

    private void rects(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rects
        Graphics G = null;
        Point lolz = MouseInfo.getPointerInfo().getLocation();
        this.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
        for (int i = 0; i < 10; i++) {
            int r, g, b;
            r = rand.nextInt(255) + 1;
            g = rand.nextInt(255) + 1;
            b = rand.nextInt(255) + 1;

            System.out.println(r + " " + g + " " + b);

            int x, y;
//            x = evt.getX() - Screen.getSize() / 2;
//            y = evt.getY() + Screen.getSize() / 2;

            x = lolz.x - 5;
            y = lolz.y - 23;

            int xx, yy;
//            xx =  rand.nextInt(10);
//            yy = rand.nextInt(10);

            xx = Integer.valueOf(txtSizeX.getText());
            yy = Integer.valueOf(txtSizeY.getText());
            // pnlColor.setBackground(new Color(r,g,b));
            G = this.getGraphics();
            G.setColor(new Color(r, g, b));
            G.fillRect(x, y, xx, yy);
            pnlColor.paint(G);
        }
    }//GEN-LAST:event_rects

    private void woo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_woo
        Graphics G = null;
        Point lolz = MouseInfo.getPointerInfo().getLocation();
        this.setCursor(new Cursor(Cursor.CROSSHAIR_CURSOR));
        for (int i = 0; i < 10; i++) {
            int r, g, b;
            r = rand.nextInt(255) + 1;
            g = rand.nextInt(255) + 1;
            b = rand.nextInt(255) + 1;

            int x, y;
//            x = evt.getX() - Screen.getSize() / 2;
//            y = evt.getY() + Screen.getSize() / 2;

            x = lolz.x - 5;
            y = lolz.y - 23;

            int xx, yy;
//            xx =  rand.nextInt(10);
//            yy = rand.nextInt(10);

            xx = Integer.valueOf(txtSizeX.getText());
            yy = Integer.valueOf(txtSizeY.getText());
            // pnlColor.setBackground(new Color(r,g,b));
            G = this.getGraphics();
            G.setColor(new Color(r, g, b));
            G.fillRect(x, y, xx, yy);
            pnlColor.paint(G);
        }
    }//GEN-LAST:event_woo

    private void hl(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hl
        if (evt.getButton() == 2) {
            Graphics G;
            G = this.getGraphics();
            G.setColor(Color.red);
            G.fillRect(0, 0, 500, 500);
            G.clearRect(0, 0, 2000, 2000);
        }
    }//GEN-LAST:event_hl

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Cake cake = new Cake();
        cake.mmmCake();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        textArea1.setText("");
        System.gc();
        System.out.println(Math.hypot(23.0, 11.0));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jLabel2.setLocation(0, 0);
        Runnable r;
        r = new Runnable() {
            
            @Override
            public void run() {
                int x = 0;
                for (int i = 0; i < 3; i++) {
                    x++;
                    System.out.println(x + " " + i);
                    for (int j = 0; j < 3; j++) {
                        jLabel2.setLocation(x, 15);
                        System.out.println("hi");
                        try {
                        Thread.sleep(10L);
                        
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    }
                   
                    

                }
            }
        };

        Thread fred = new Thread(r);
        
        fred.run();


    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnswer;
    private javax.swing.JButton btnColorz;
    private javax.swing.JButton btnDecrypt;
    private javax.swing.JButton btnEncrypt;
    private javax.swing.JButton btnShowAnswer;
    private javax.swing.JButton btnStart;
    private java.awt.Button button1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCorrect;
    private javax.swing.JLabel lblDecryptedPassword;
    private javax.swing.JLabel lblEncryptedPassword;
    private javax.swing.JLabel lblEnterPassword;
    private javax.swing.JLabel lblIncorrect;
    private javax.swing.JLabel lblNumOne;
    private javax.swing.JLabel lblNumTwo;
    private javax.swing.JLabel lblOperator;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel pnlColor;
    private java.awt.TextArea textArea1;
    private javax.swing.JTextPane txtColours;
    private javax.swing.JPasswordField txtEnterPassword;
    private javax.swing.JTextField txtGuess;
    private javax.swing.JTextField txtSizeX;
    private javax.swing.JTextField txtSizeY;
    // End of variables declaration//GEN-END:variables

    private int genNums() {
        numOne = rand.nextInt(10) + 1;
        lblNumOne.setText(String.valueOf(numOne));

        numTwo = rand.nextInt(10) + 1;
        lblNumTwo.setText(String.valueOf(numTwo));

        sumTotal = numOne + numTwo;

        return sumTotal;
    }

    private int genMoreNums() {
        randOper = rand.nextInt(4) + 1;
        switch (randOper) {
            case 1:
                operChar = "+";
                lblOperator.setText(operChar);

                numOne = rand.nextInt(10) + 1;
                lblNumOne.setText(String.valueOf(numOne));

                numTwo = rand.nextInt(10) + 1;
                lblNumTwo.setText(String.valueOf(numTwo));

                sumTotal = numOne + numTwo;
                break;

            case 2:
                operChar = "-";
                lblOperator.setText(operChar);

                numOne = rand.nextInt(10) + 1;
                lblNumOne.setText(String.valueOf(numOne));

                numTwo = rand.nextInt(10) + 1;
                lblNumTwo.setText(String.valueOf(numTwo));

                sumTotal = numOne - numTwo;
                break;

            case 3:
                operChar = "X";
                lblOperator.setText(operChar);

                numOne = rand.nextInt(10) + 1;
                lblNumOne.setText(String.valueOf(numOne));

                numTwo = rand.nextInt(10) + 1;
                lblNumTwo.setText(String.valueOf(numTwo));

                sumTotal = numOne * numTwo;
                break;

            case 4:
                operChar = "÷";
                lblOperator.setText(operChar);

                numOne = rand.nextInt(10) + 1;
                lblNumOne.setText(String.valueOf(numOne));

                numTwo = rand.nextInt(10) + 1;
                lblNumTwo.setText(String.valueOf(numTwo));

                sumTotal = numOne / numTwo;

                if (sumTotal <= 0) {
                    System.out.println("An answer to a division calculation was"
                            + " less than or equal to 0 and a new calculation "
                            + "was set. ");
                    System.out.println("The caclulation was " + numOne
                            + " ÷ " + numTwo + " = " + sumTotal);
                    genMoreNums();
                    break;
                }
                break;

        }
        if (sumTotal < 0) {
            txtGuess.setText("-");
        } else {
            txtGuess.setText("");
        }
        return sumTotal;
    }

    private boolean checkAnswer() {
        guess = txtGuess.getText();
        if ((guess.length() != 0) && (!"-".equals(guess))
                && (!"blank, hit start :)".equals(guess))) {

            if (guess.equals(String.valueOf(sumTotal))) {
                answerCorrect++;

                lblCorrect.setText("Correct Answers: "
                        + String.valueOf(answerCorrect));

                System.out.println("Correct! " + numOne + " " + operChar + " "
                        + numTwo + " = " + sumTotal);

                lblOutput.setText("Correct! " + numOne + " " + operChar + " "
                        + numTwo + " = " + sumTotal);

                txtGuess.setText("");
                genMoreNums();
                txtGuess.grabFocus();
                return true;

            } else {
                answerIncorrect++;

                lblIncorrect.setText("Incorrect Answers: "
                        + String.valueOf(answerIncorrect));
                System.out.println("Incorrect!");

                lblOutput.setText("Incorrect, try again...");
                return false;
            }

        } else {
            txtGuess.setText("blank, hit start :)");
            return false;
        }
    }
}
